spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    initialization-mode: always
    continue-on-error: true
    url: jdbc:h2:file:./mentoria-db
    username: sa
    password:
    data: classpath:alunos.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true